version: 18
jobs:
- name: push to github
  jobExecutor: genshin-map-shell
  steps:
  - !PushRepository
    name: push to github
    remoteUrl: https://github.com/kongying-tavern/map_register_v3.git
    userName: momentderek
    passwordSecret: push-secret
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: '"Log" contains "无法访问"'
  maxRetries: 10
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
- name: builld
  steps:
  - !CommandStep
    name: cd the workspace and pull from oneDev
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - cd @secret:workspace-path@
      - git checkout -q beta
      - git checkout . && git clean -xdf -e .env.*.local
      - git pull -r --autostash
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: download dependency
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - cd @secret:workspace-path@
      - sudo rm -rf ./node_modules
      - pnpm i
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - cd @secret:workspace-path@
      - pnpm run build
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: publish
    artifacts: 'dist/**'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
