export { default as IconGithub } from './IconGithub.vue'
export { default as IconSetting } from './IconSetting.vue'
export { default as IconPound } from './IconPound.vue'
export { default as IconTitleSerif } from './IconTitleSerif.vue'
export { default as IconDocument } from './IconDocument.vue'
export { default as IconDocumentRegex } from './IconDocumentRegex.vue'
