/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * marker_single_punctuate; 点位提交信息
 */
export type DTS_12745505 = DTS_12745503 & {
  /**
   * 申请者ID
   */
  author?: number
  /**
   * 状态; 0:暂存 1:审核中 2:不通过
   */
  status?: string
  /**
   * 打点提交ID
   */
  punctuateId?: string
  /**
   * 审核备注
   */
  auditRemark?: string
  /**
   * 操作类型; 1: 新增 2: 修改 3: 删除
   */
  methodType?: string
}
/**
 * marker_extra_punctuate; 点位额外字段提交信息
 */
export type DTS_12745525 = DTS_12745501 & {
  /**
   * 申请者ID
   */
  author?: number
  /**
   * 状态; 0:暂存 1:审核中 2:不通过
   */
  status?: string
  /**
   * 打点提交ID
   */
  punctuateId?: string
  /**
   * 审核备注
   */
  auditRemark?: string
  /**
   * 操作类型; 1: 新增 2: 修改 3: 删除
   */
  methodType?: string
}

/**
 * 全接口请求体的类型与响应成功的类型
 */
export interface ApiTypeMap {
  post?: {
    '/tag/get/type/list'?: TagGetTypeList
    '/tag/type'?: TagType
    '/tag/get/list'?: TagGetList
    '/tag/get/single/{name}'?: TagGetSingleName
    '/tag/{tagName}/{iconId}'?: TagTagNameIconId
    '/tag/updateType'?: TagUpdateType
    '/icon/get/type/list'?: IconGetTypeList
    '/icon/type'?: IconType
    '/icon/get/list'?: IconGetList
    '/icon/get/single/{iconId}'?: IconGetSingleIconId
    '/icon/update'?: IconUpdate
    '/area/get/list'?: AreaGetList
    '/area/get/{areaId}'?: AreaGetAreaId
    '/area/'?: Area
    '/item/get/common'?: ItemGetCommon
    '/item/get/type/{self}'?: ItemGetTypeSelf
    '/item/type'?: ItemType
    '/item/type/move/{targetTypeId}'?: ItemTypeMoveTargetTypeId
    '/item/get/list'?: ItemGetList
    '/item/update/{editSame}'?: ItemUpdateEditSame
    '/item/join/{typeId}'?: ItemJoinTypeId
    '/marker/punctuate/author/get/page'?: MarkerPunctuateAuthorGetPage
    '/marker/punctuate/author/get/page_single/{authorId}'?: MarkerPunctuateAuthorGetPageSingleAuthorId
    '/marker/punctuate/author/get/page_extra/{authorId}'?: MarkerPunctuateAuthorGetPageExtraAuthorId
    '/marker/punctuate/author/single'?: MarkerPunctuateAuthorSingle
    '/marker/punctuate/author/extra'?: MarkerPunctuateAuthorExtra
    '/marker/punctuate/check/get/id'?: MarkerPunctuateCheckGetId
    '/marker/punctuate/check/get/list_byinfo'?: MarkerPunctuateCheckGetListByinfo
    '/marker/punctuate/check/get/list_byid'?: MarkerPunctuateCheckGetListByid
    '/marker/punctuate/check/get/page/all'?: MarkerPunctuateCheckGetPageAll
    '/marker/punctuate/check/ok/{punctuateId}'?: MarkerPunctuateCheckOkPunctuateId
    '/marker/punctuate/check/fail/{punctuateId}'?: MarkerPunctuateCheckFailPunctuateId
    '/marker/get/id'?: MarkerGetId
    '/marker/get/list_byinfo'?: MarkerGetListByinfo
    '/marker/get/list_byid'?: MarkerGetListByid
    '/marker/get/page'?: MarkerGetPage
    '/marker/single'?: MarkerSingle
    '/marker/extra'?: MarkerExtra
    '/oauth/token'?: OauthToken
    '/user/register'?: UserRegister
    '/user/update'?: UserUpdate
    '/user/update_password'?: UserUpdatePassword
    '/api/public/upload'?: ApiPublicUpload
    '/api/admin/mkdir'?: ApiAdminMkdir
    '/history/get/list'?: HistoryGetList
  }
  put?: {
    '/tag/type'?: TagType1
    '/tag/{tagName}'?: TagTagName
    '/icon/type'?: IconType1
    '/icon/add'?: IconAdd
    '/area/add'?: AreaAdd
    '/item/common'?: ItemCommon
    '/item/type'?: ItemType1
    '/item'?: Item
    '/item/copy/{areaId}'?: ItemCopyAreaId
    '/marker/punctuate/author/single'?: MarkerPunctuateAuthorSingle1
    '/marker/punctuate/author/extra'?: MarkerPunctuateAuthorExtra1
    '/marker/punctuate/author/push/{authorId}'?: MarkerPunctuateAuthorPushAuthorId
    '/marker/single'?: MarkerSingle1
    '/marker/extra'?: MarkerExtra1
    '/role/user'?: RoleUser
  }
  delete?: {
    '/tag/type/{typeId}'?: TagTypeTypeId
    '/tag/{tagName}'?: TagTagName1
    '/icon/type/{typeId}'?: IconTypeTypeId
    '/icon/delete/{iconId}'?: IconDeleteIconId
    '/area/{areaId}'?: AreaAreaId
    '/item/common'?: ItemCommon1
    '/item/type'?: ItemType2
    '/item/{itemId}'?: ItemItemId
    '/marker/punctuate/author/{authorId}/{punctuateId}'?: MarkerPunctuateAuthorAuthorIdPunctuateId
    '/marker/punctuate/check/{punctuateId}'?: MarkerPunctuateCheckPunctuateId
    '/marker/{markerId}'?: MarkerMarkerId
    '/user/{workId}'?: UserWorkId
    '/role/user'?: RoleUser1
  }
  get?: {
    '/user/info/{userId}'?: UserInfoUserId
    '/role/list'?: RoleList
  }
}
/**
 * 列出分类; 列出标签的分类，parentID为-1的时候为列出所有的根分类，可分页
 */
export interface TagGetTypeList {
  request?: DTS_11765445 & DTS_11765451
  response?: DTS_11765446
}
/**
 * 分页请求
 */
export interface DTS_11765445 {
  /**
   * 当前页，从0开始; 从0开始
   */
  current?: number
  /**
   * 每页大小，默认为10; 默认为10
   */
  size?: number
}
/**
 * 分类遍历
 */
export interface DTS_11765451 {
  /**
   * 父级类型ID列表
   */
  typeIdList?: number[]
}
/**
 * 响应信息
 */
export interface DTS_11765446 {
  /**
   * 返回标记; 成功标记=0，失败标记=1
   */
  code: number
  data: {}
  /**
   * 响应时间
   */
  time: string
  /**
   * 返回信息
   */
  message: string
}
/**
 * 修改分类;
 */
export interface TagType {
  request?: DTS_12745496
  response?: DTS_11765446
}
/**
 * tag_type
 */
export interface DTS_12745496 {
  /**
   * 分类名称
   */
  name?: string
  /**
   * 父级分类ID; -1为根分类
   */
  parent?: string
  /**
   * 分类ID
   */
  typeId?: string
  /**
   * 是否为末端类型
   */
  isFinal: string
}
/**
 * 列出标签; 可按照分类（分类需保证为末端分类）进行查询，也可给出需要查询url的tag名称列表，可分页
 */
export interface TagGetList {
  request?: DTS_11765445 & {
    tagList?: string[]
    typeIdList?: number[]
  }
  response?: DTS_11765446
}
/**
 * 获取单个标签信息;
 */
export interface TagGetSingleName {
  request?: undefined
  response?: DTS_11765446
}
/**
 * 修改标签关联;
 */
export interface TagTagNameIconId {
  request?: undefined
  response?: DTS_11765446
}
/**
 * 修改标签的分类信息; 本接口仅在后台使用，故分离出来
 */
export interface TagUpdateType {
  request?: DTS_12745493
  response?: DTS_11765446
}
/**
 * tag
 */
export interface DTS_12745493 {
  /**
   * 标签名
   */
  name?: string
  /**
   * 图标ID
   */
  iconId?: string
  /**
   * 图标url
   */
  url: string
  /**
   * 标签类型ID列表
   */
  typeIdList?: number[]
}
/**
 * 列出分类; 列出图标的分类，typeId为-1的时候为列出所有的根分类
 */
export interface IconGetTypeList {
  request?: DTS_11765445 & DTS_11765451
  response?: DTS_11765446
}
/**
 * 修改分类; 由类型ID来定位修改一个分类
 */
export interface IconType {
  request?: DTS_12745499
  response?: DTS_11765446
}
/**
 * icon_type
 */
export interface DTS_12745499 {
  /**
   * 分类名称
   */
  name?: string
  /**
   * 父级分类ID; -1为根分类
   */
  parent?: string
  /**
   * 分类ID
   */
  typeId?: string
  /**
   * 是否为末端类型
   */
  isFinal?: boolean
}
/**
 * 列出图标; 可按照分类（分类需保证为末端分类）和上传者进行查询，也可根据ID批量查询，可分页
 */
export interface IconGetList {
  request?: DTS_11765445 &
    DTS_11765451 & {
      creator?: number
      iconIdList?: number[]
    }
  response?: DTS_11765446
}
/**
 * 获取单个图标信息;
 */
export interface IconGetSingleIconId {
  request?: undefined
  response?: DTS_11765446
}
/**
 * 修改图标信息; 由icon_id定位修改一个icon
 */
export interface IconUpdate {
  request?: DTS_12745494
  response?: DTS_11765446
}
/**
 * icon; 图标信息
 */
export interface DTS_12745494 {
  /**
   * 图标url
   */
  url?: string
  /**
   * 图标ID
   */
  iconId?: string
  /**
   * 图标名称
   */
  iconName?: string
  /**
   * 创建者ID
   */
  creatorId?: string
  /**
   * 图标类型ID列表
   */
  typeIdList?: number[]
}
/**
 * 列出地区; 可根据父级地区id列出子地区列表
 */
export interface AreaGetList {
  request?: {
    parentId?: number
    isTraverse?: boolean
  }
  response?: DTS_12745486
}
/**
 * area_list; 地区列表
 */
export interface DTS_12745486 {
  /**
   * 数据
   */
  areaList: DTS_12745490[]
}
export interface DTS_12745490 {
  /**
   * 地区名称
   */
  name?: string
  /**
   * 地区说明
   */
  content?: string
  /**
   * 父级地区ID（无父级则为-1）
   */
  parentId?: number
  /**
   * 地区ID
   */
  areaId: number
  /**
   * 图标标签
   */
  iconTag?: string
  /**
   * 是否为末端地区
   */
  isFinal: boolean
  /**
   * 排序
   */
  sortIndex?: string
  /**
   * 显隐方式
   */
  hiddenFlag?: string
}
/**
 * 获取单个地区信息;
 */
export interface AreaGetAreaId {
  request?: undefined
  response?: DTS_11765446
}
/**
 * 修改地区;
 */
export interface Area {
  request?: DTS_127454901
  response?: DTS_11765446
}
/**
 * area; 地区信息
 */
export interface DTS_127454901 {
  /**
   * 地区名称
   */
  name?: string
  /**
   * 地区说明
   */
  content?: string
  /**
   * 父级地区ID（无父级则为-1）
   */
  parentId?: number
  /**
   * 地区ID
   */
  areaId: number
  /**
   * 图标标签
   */
  iconTag?: string
  /**
   * 是否为末端地区
   */
  isFinal: boolean
  /**
   * 排序
   */
  sortIndex?: string
  /**
   * 显隐方式
   */
  hiddenFlag?: string
}
/**
 * 列出地区公用物品;
 */
export interface ItemGetCommon {
  request?: DTS_11765445
  response?: DTS_11765446
}
/**
 * 列出物品类型; 不递归遍历，只遍历子级
 */
export interface ItemGetTypeSelf {
  request?: DTS_11765451 & DTS_11765445
  response?: DTS_11765446
}
/**
 * 修改物品类型; 修改物品类型
 */
export interface ItemType {
  request?: DTS_12745491
  response?: DTS_11765446
}
/**
 * type; 物品类型
 */
export interface DTS_12745491 {
  /**
   * 类型名
   */
  name?: string
  /**
   * 类型补充说明
   */
  content?: string
  /**
   * 类型ID
   */
  typeId?: string
  /**
   * 图标标签
   */
  iconTag?: string
  /**
   * 父级类型ID（无父级则为-1）
   */
  parentId?: string
  /**
   * 是否为末端类型
   */
  isFinal?: string
  /**
   * 排序
   */
  sortIndex?: string
  /**
   * 显隐方式
   */
  hiddenFlag?: string
}
/**
 * 批量移动类型为目标类型的子类型; 将类型批量移动到某个类型下作为其子类型
 */
export interface ItemTypeMoveTargetTypeId {
  request?: number[]
  response?: {}
}
/**
 * 根据筛选条件列出物品信息; 传入的物品类型ID和地区ID列表，必须为末端的类型或地区
 */
export interface ItemGetList {
  request?: DTS_11765445 & {
    areaIdList?: number[]
    typeIdList?: number[]
  }
  response?: DTS_11765446
}
/**
 * 修改物品; 提供修改同名物品功能，默认关闭
 */
export interface ItemUpdateEditSame {
  request?: DTS_12745488[]
  response?: DTS_11765446
}
/**
 * item; 物品信息
 */
export interface DTS_12745488 {
  /**
   * 物品名称
   */
  name?: string
  /**
   * 物品ID
   */
  itemId?: string
  /**
   * 默认描述模板
   */
  defaultContent?: string
  /**
   * 图标标签
   */
  iconTag?: string
  /**
   * 物品类型ID列表
   */
  typeIdList?: number[]
  /**
   * 地区ID
   */
  areaId?: number
  /**
   * 物品显示类型
   */
  iconStyleType?: number
  /**
   * 显隐方式
   */
  hiddenFlag?: number
  /**
   * 排序序号
   */
  sortIndex?: number
  /**
   * 默认刷新时间
   */
  defaultRefreshTime?: number
  /**
   * 默认点位计数
   */
  defaultCount?: number
}
/**
 * 将物品加入某一类型; 根据物品ID列表批量加入
 */
export interface ItemJoinTypeId {
  request?: number[]
  response?: DTS_11765446
}
/**
 * 分页查询所有打点信息; 分页查询所有打点信息
 */
export interface MarkerPunctuateAuthorGetPage {
  request?: DTS_11765445
  response?: DTS_11765446
}
/**
 * 分页查询自己提交的未通过的打点信息（不包含额外字段）; 分页查询自己提交的未通过的打点信息（不包含额外字段）（打点员的API）
 */
export interface MarkerPunctuateAuthorGetPageSingleAuthorId {
  request?: DTS_11765445
  response?: DTS_11765446
}
/**
 * 分页查询自己提交的未通过的打点信息（只包含额外字段） ; 分页查询自己提交的未通过的打点信息（只包含额外字段） （打点员的API）
 */
export interface MarkerPunctuateAuthorGetPageExtraAuthorId {
  request?: DTS_11765445
  response?: DTS_11765446
}
/**
 * 修改自身未提交的暂存点位（不包括额外字段）; 根据点位ID修改点位
 */
export interface MarkerPunctuateAuthorSingle {
  request?: DTS_12745505
  response?: DTS_11765446
}
/**
 * marker_single; 不含额外信息的点位模型
 */
export interface DTS_12745503 {
  /**
   * 点位坐标
   */
  position?: string
  /**
   * 点位说明
   */
  content?: string
  /**
   * 点位图片
   */
  picture?: string
  /**
   * 点位初始标记者
   */
  markerCreatorId?: number
  /**
   * 点位图片上传者
   */
  pictureCreatorId?: number
  /**
   * 点位视频
   */
  videoPath?: string
  /**
   * 原有点位ID
   */
  original_marker_id?: number
  /**
   * 刷新时间
   */
  refreshTime?: number
  /**
   * 显隐方法
   */
  hiddenFlag?: number
  /**
   * 点位标题
   */
  markerTitle?: string
  /**
   * 点位物品ID列表
   */
  itemList?: DTS_12745524[]
  /**
   * 点位ID
   */
  id?: number
}
export interface DTS_12745524 {
  /**
   * 物品ID
   */
  itemId: number
  /**
   * 物品计数
   */
  count: number
}
/**
 * 修改自身未提交的暂存点位的额外字段; 根据点位ID修改点位
 */
export interface MarkerPunctuateAuthorExtra {
  request?: DTS_12745525
  response?: DTS_11765446
}
/**
 * marker_extra; 点位额外字段
 */
export interface DTS_12745501 {
  /**
   * 额外特殊字段具体内容; json格式，详情参见“点位额外字段文档”
   */
  markerExtraContent?: string
  /**
   * 父点位ID; 根据点位类型，此字段可能不存在或者为空
   */
  parentId?: number
  /**
   * 关联其他点位Flag; 1为关联了其他点位，需要做关联工作
   */
  isRelated?: string
  /**
   * 点位ID
   */
  markerId?: number
}
/**
 * 根据各种条件筛选打点ID; 支持根据末端地区、末端类型、物品、提交者来进行查询，地区、类型、物品查询不能同时生效，同时存在时报错
 */
export interface MarkerPunctuateCheckGetId {
  request?: {
    authorList?: number[]
    itemIdList?: number[]
    areaIdList?: number[]
    typeIdList?: number[]
  }
  response?: DTS_11765446
}
/**
 * 根据各种条件筛选打点信息; 支持根据末端地区、末端类型、物品、提交者来进行查询，地区、类型、物品查询不能同时生效，同时存在时报错
 */
export interface MarkerPunctuateCheckGetListByinfo {
  request?: {
    authorList?: number[]
    itemIdList?: number[]
    areaIdList?: number[]
    typeIdList?: number[]
  }
  response?: DTS_11765446
}
/**
 * 通过打点ID列表查询打点信息; 通过打点ID列表查询打点信息
 */
export interface MarkerPunctuateCheckGetListByid {
  request?: number[]
  response?: DTS_11765446
}
/**
 * 分页查询所有打点信息（包括暂存）; 分页查询所有打点信息
 */
export interface MarkerPunctuateCheckGetPageAll {
  request?: DTS_11765445
  response?: DTS_11765446
}
/**
 * 通过点位审核; 通过审核，返回点位ID（如果是新建点位，则为新点位ID），通过额外字段关联的点位也会自动通过审核（但不会返回关联点位的ID）
 */
export interface MarkerPunctuateCheckOkPunctuateId {
  request?: undefined
  response?: DTS_11765446
}
/**
 * 驳回点位审核; 驳回的点位和通过额外字段关联的点位会回到暂存区
 */
export interface MarkerPunctuateCheckFailPunctuateId {
  request?: string
  response?: DTS_11765446
}
/**
 * 根据各种条件筛选查询点位ID; 支持根据末端地区、末端类型、物品来进行查询，三种查询不能同时生效，同时存在时报错
 */
export interface MarkerGetId {
  request?: {
    areaIdList?: number[]
    typeIdList?: number[]
    itemIdList?: number[]
    /**
     * 默认为0，不获取，为1时只获取测试点位
     */
    getBeta?: number
  }
  response?: DTS_11765446
}
/**
 * 根据各种条件筛选查询点位信息; 支持根据末端地区、末端类型、物品来进行查询，三种查询不能同时生效，同时存在时报错
 */
export interface MarkerGetListByinfo {
  request?: {
    areaIdList?: number[]
    typeIdList?: number[]
    itemIdList?: number[]
    /**
     * 默认为0，不获取，为1时只获取测试点位
     */
    getBeta?: number
  }
  response?: DTS_11765446
}
/**
 * 通过ID列表查询点位信息; 通过ID列表来进行查询点位信息
 */
export interface MarkerGetListByid {
  request?: number[]
  response?: DTS_11765446
}
/**
 * 分页查询所有点位信息; 分页查询所有点位信息
 */
export interface MarkerGetPage {
  request?: DTS_11765445
  response?: DTS_11765446
}
/**
 * 修改点位（不包括额外字段）; 根据点位ID修改点位
 */
export interface MarkerSingle {
  request?: DTS_12745503
  response?: DTS_11765446
}
/**
 * 修改点位额外字段; 根据点位ID修改点位额外字段
 */
export interface MarkerExtra {
  request?: DTS_12745501[]
  response?: DTS_11765446
}
/**
 * oauth刷新密钥;
 */
export interface OauthToken {
  request?: {
    grant_type: string
    username: string
    password: string
  }
  response?: {}
}
/**
 * 注册用户;
 */
export interface UserRegister {
  request?: DTS_12196067
  response?: DTS_11765446
}
/**
 * user
 */
export interface DTS_12196067 {
  /**
   * 用户名
   */
  username: string
  /**
   * 密码
   */
  password: string
  /**
   * 昵称
   */
  nickname: string
  /**
   * QQ
   */
  qq: string
  /**
   * 手机号
   */
  phone: string
  /**
   * 角色列表
   */
  roleLIst: DTS_12196071[]
  /**
   * 用户ID
   */
  userId: number
}
export interface DTS_12196071 {
  /**
   * 角色名
   */
  name: string
  /**
   * 角色代码（英文大写）
   */
  code: string
  /**
   * 角色层级（越大级别越高）
   */
  sort: number
  /**
   * 角色ID
   */
  id: number
}
/**
 * 更新用户信息;
 */
export interface UserUpdate {
  request?: DTS_12196067
  response?: DTS_11765446
}
/**
 * 更新用户密码;
 */
export interface UserUpdatePassword {
  request?: DTS_12196067 & {
    oldPassword?: string
  }
  response?: DTS_11765446
}
/**
 * 上传图片到指定目录; 上传图片，文件夹不存在会返回错误
 */
export interface ApiPublicUpload {
  request?: undefined
  response?: {
    code: number
    message: string
    data: string | null
  }
}
/**
 * 新建文件夹; 新建文件夹，父级文件夹不存在会返回错误
 */
export interface ApiAdminMkdir {
  request?: {
    path: string
  }
  response?: {
    code: number
    message: string
    data: string | null
  }
}
/**
 * 历史记录分页查询;
 */
export interface HistoryGetList {
  request?: {
    /**
     * 当前页，从0开始
     */
    current: number
    /**
     * 每页大小，默认为10
     */
    size: number
    /**
     * 记录类型 3-item 4-marker
     */
    type: number
    /**
     * 类型下的ID(配合记录类型使用)
     */
    id: string[]
  }
  response?: {}
}
/**
 * 新增分类; 类型id在创建后返回
 */
export interface TagType1 {
  request?: DTS_12745496
  response?: DTS_11765446
}
/**
 * 创建标签; 只创建一个空标签
 */
export interface TagTagName {
  request?: undefined
  response?: DTS_11765446
}
/**
 * 新增分类; 类型id在创建后返回
 */
export interface IconType1 {
  request?: DTS_12745499
  response?: DTS_11765446
}
/**
 * 新增图标; 1. 无需指定icon的id，id由系统自动生成并在响应中返回
 * 2. 一组name和creator需要唯一（允许单一重复）
 */
export interface IconAdd {
  request?: {
    url: string
    typeIdList: number[]
    name: string
    creator: string
    iconId: string
  }
  response?: DTS_11765446
}
/**
 * 新增地区; 返回新增地区ID
 */
export interface AreaAdd {
  request?: DTS_127454901
  response?: DTS_11765446
}
/**
 * 新增地区公用物品; 通过ID列表批量添加地区公用物品
 */
export interface ItemCommon {
  request?: number[]
  response?: DTS_11765446
}
/**
 * 添加物品类型; 成功后返回新的类型ID
 */
export interface ItemType1 {
  request?: DTS_12745491
  response?: DTS_11765446
}
/**
 * 新增物品; 新建成功后会返回新物品ID
 */
export interface Item {
  request?: DTS_12745488
  response?: DTS_11765446
}
/**
 * 复制物品到地区; 根据物品ID列表复制物品到新地区，此操作会递归复制类型及父级类型。
 * 会返回新的物品列表与新的类型列表，用于反映新的ID
 */
export interface ItemCopyAreaId {
  request?: number[]
  response?: DTS_11765446
}
/**
 * 提交暂存点位（不含额外字段）; 成功则返回打点提交ID
 */
export interface MarkerPunctuateAuthorSingle1 {
  request?: DTS_12745505
  response?: DTS_11765446
}
/**
 * 提交暂存点位额外字段; 在涉及的所有点位已经暂存后在使用该api
 */
export interface MarkerPunctuateAuthorExtra1 {
  request?: DTS_12745525
  response?: DTS_11765446
}
/**
 * 将暂存点位提交审核; 将暂存点位提交审核
 */
export interface MarkerPunctuateAuthorPushAuthorId {
  request?: DTS_12745505
  response?: DTS_11765446
}
/**
 * 新增点位（不包括额外字段）; 新增完成后返回点位ID
 */
export interface MarkerSingle1 {
  request?: DTS_12745503
  response?: DTS_11765446
}
/**
 * 新增点位额外字段信息; 需保证额外字段的点位都已经添加成功
 */
export interface MarkerExtra1 {
  request?: DTS_12745501
  response?: DTS_11765446
}
/**
 * 将角色赋予给用户; 将角色赋予给用户
 */
export interface RoleUser {
  request?: DTS_12832113
  response?: DTS_11765446
}
/**
 * roleLink; 用户-角色关联
 */
export interface DTS_12832113 {
  userId: number
  roleId: number
}
/**
 * 删除分类; 这个操作会递归删除，请在前端做二次确认
 */
export interface TagTypeTypeId {
  request?: undefined
  response?: DTS_11765446
}
/**
 * 删除标签; 需要确保已经没有条目在使用这个标签，否则会删除失败
 */
export interface TagTagName1 {
  request?: undefined
  response?: {}
}
/**
 * 删除分类; 这个操作会递归删除，请在前端做二次确认
 */
export interface IconTypeTypeId {
  request?: undefined
  response?: DTS_11765446
}
/**
 * 删除图标;
 */
export interface IconDeleteIconId {
  request?: undefined
  response?: DTS_11765446
}
/**
 * 删除地区; 此操作会递归删除，请在前端做二次确认
 */
export interface AreaAreaId {
  request?: undefined
  response?: DTS_11765446
}
/**
 * 删除地区公用物品; 批量删除
 */
export interface ItemCommon1 {
  request?: number[]
  response?: DTS_11765446
}
/**
 * 删除物品类型; 批量递归删除物品类型，需在前端做二次确认
 */
export interface ItemType2 {
  request?: number[]
  response?: DTS_11765446
}
/**
 * 删除物品; 根据物品ID删除物品
 */
export interface ItemItemId {
  request?: number[]
  response?: DTS_11765446
}
/**
 * 删除自己未通过的提交点位; 根据提交ID来删除提交点位，会对打点员ID进行校验
 */
export interface MarkerPunctuateAuthorAuthorIdPunctuateId {
  request?: number[]
  response?: DTS_11765446
}
/**
 * 删除提交点位; 根据提交ID来删除提交点位
 */
export interface MarkerPunctuateCheckPunctuateId {
  request?: number[]
  response?: DTS_11765446
}
/**
 * 删除点位; 根据点位ID删除点位
 */
export interface MarkerMarkerId {
  request?: number[]
  response?: DTS_11765446
}
/**
 * 删除用户;
 */
export interface UserWorkId {
  request?: number
  response?: DTS_11765446
}
/**
 * 将角色从用户剥夺; 将角色从用户剥夺
 */
export interface RoleUser1 {
  request?: DTS_12832113
  response?: DTS_11765446
}
/**
 * 获取用户信息; 仅能获得权限内的信息
 */
export interface UserInfoUserId {
  request?: undefined
  response?: DTS_12196067
}
/**
 * 返回可用角色列表; 返回可用角色列表
 */
export interface RoleList {
  request?: undefined
  response?: DTS_11765446
}
