export { default as IconCreator } from './IconCreator.vue'
export { default as IconDetailForm } from './IconDetailForm.vue'
export { default as IconEditor } from './IconEditor.vue'
export { default as IconImageEditor } from './IconImageEditor.vue'
export { default as IconTable } from './IconTable.vue'
