export { default as AreaCreator } from './AreaCreator.vue'
export { default as AreaDeleteConfirm } from './AreaDeleteConfirm.vue'
export { default as AreaDetailForm } from './AreaDetailForm.vue'
export { default as AreaEditor } from './AreaEditor.vue'
export { default as AreaTable } from './AreaTable.vue'
